export const UPDATE_EMAIL ='UPDATE_EMAIL';
export const UPDATE_PASSWORD ='UPDATE_PASSWORD';
export const UPDATE_AUTHENTICATION ='UPDATE_AUTHENTICATION';
export const ADD_PRODUCT_TO_CART ='ADD_PRODUCT_TO_CART';
export const INCREASE_QUANTITY ='INCREASE_QUANTITY';
export const DECREASE_QUANTITY ='DECREASE_QUANTITY';
export const CLEAR_PRODUCT ='CLEAR_PRODUCT';